### ISSUE TITLE
Show ingredients before start recipe

### ISSUE THREAD

**Issue by seline1511** [fkunneman/Chefbot_NCF#13]
Before the user starts cooking, they want to know the needed ingredients, so they can make sure they have everything they need

**Comment by seline1511** [comment]
Cooking utensils can also be included here.

**Comment by koenhindriks** [comment]
> Cooking utensils can also be included here.

I would make that a separate issue.

**Comment by seline1511** [comment]
**In agent_recipes.json** the recipe is divided into two keys; preliminaries and recipe steps. In preliminaries the ingredients and cooking utensils are listed. The ingredients consist of a txt_standard that always says: Dit zijn de ingredienten die je nodig hebt:”  and a numbered list of all the ingredients. There is also a part that shows images of the ingredients, this is called “img_howto” the url is placed to show images of the ingredients.

**In dialog_manager.py** in the function start_recipe the keys mentioned above are created. These are added in line 219 and 220:
self.active_recipe['Recipe_steps'] = self.recipes['Recipe'][name]['Recipe_steps']
self.active_recipe['preliminaries'] = self.recipes['Recipe'][name]['preliminaries']

**In the infostate_tracker.py** in the init of the ISU class preliminaries and explanations are added as a dict to the private state. This is also done in the clear function. Furthermore, plan_wide now shows all steps. And explanations shows the details to each step. 

**In the natural_language_genarator.py** a function ingredient_steps is added. Every ingredient in the recipe is added to the response. In addition, the images are printed.

**In the standard_moves.py** a new class IngredientStep(Move) is made, this is the first step after the recipe conformation.
