### ISSUE TITLE
Show cooking utensils before start recipe

### ISSUE THREAD

**Issue by koenhindriks** [fkunneman/Chefbot_NCF#17]
Before the agent starts walking the user through a recipe, it should check with the user whether all cooking utensils that are needed are available. A basic way to do this is to display all cooking utensils on the screen and ask the user whether these are available.

We could also offer a more advanced option and ask the user whether we should talk the user through the needed cooking utensils if desired.

**Comment by cayadehaas** [comment]
In agent_recipes.json the recipe is divided into two keys; preliminaries and recipe steps. In preliminaries the ingredients and cooking utensils are listed. Under img_howto the url is placed to show images of the cooking utensils.

**Comment by cayadehaas** [comment]
In dialog_manager.py in the function start_recipe the keys mentioned above are created. So we have both: 
    self.active_recipe['Recipe_steps'] = self.recipes['Recipe'][name]['Recipe_steps']
    self.active_recipe['preliminaries'] = self.recipes['Recipe'][name]['preliminaries']

**Comment by cayadehaas** [comment]
In the infostate_tracker.py: in the init of the ISU class preliminaries and explanations are added as a dict to the private state. This is also done in the clear function. Furthermore, plan_wide now shows all steps. And explanantions shows the details to each step.

**Comment by cayadehaas** [comment]
In the NLG class, a function cooking_utensils list is added. For every cooking utensil in the recipe, the cooking utensil is added to the response. In addition, the images are printed.

**Comment by cayadehaas** [comment]
In the standard_moves.py a new class CookingUtensilsList is made.
